### ISSUE TITLE
Not respecting /etc/fstab entries when UUID is quoted

### ISSUE THREAD

**Issue by tarelda** [rbrito/usbmount#15]
Exactly as in title. Probably needs regex modification.

**Comment by mathieulj** [comment]
Care to elaborate so that someone can better understand your issue?

Ex.
1. What are you doing?
2. What do you expect will happen?
3. What really happens?
4. What do you believe is a factor in the issue?
5. What platform, distribution, software version are you using?
6. What version of the package are you using?

From your post all I can tell is that 2 and 3 dont match and that 4 has something to do with a/some/all UUID(s) beeing quoted or not in /etc/fstab although it doesnt specify if they are even related to the expected behaviour of this package.

**Comment by mathieulj** [comment]
Thank you for the extra information, it allowed me to understand your issue and the fix was indeed a simple regex modification.
