### ISSUE TITLE
Cannot chown target file on exFAT USB-drive

### ISSUE THREAD

**Issue by Supr-A** [rbrito/usbmount#30]
Hello.

I've installed usbmount 0.0.24 on Ubuntu Server v20.04.1 and added `exfat` to `/etc/usbmount/usbmount.conf`'s variable `FILESYSTEMS`. USB Flash Drive with exFAT filesystem has been successfully mounted after plug-in, but when I copy files from server's HDD to USB Flash Drive in Midnight Commander I get the following error after each file `Cannot chown target file "/media/usb/test.jpg" Operation not permitted (1)`. As I understand this is because exFAT doesn't support chown. Is it possible to turn off chown attempts for all drives that don't support it?

**Comment by mathieulj** [comment]
Perhaps I am misunderstanding something so please feel free to correct me on this but if I understand correctly you are saying that Midnight commander is throwing errors because it chowns on copy without checking if the file system supports it? If that is correct, this should be reported on their issue tracker rather than here as usbmount does not interact with the users of the mount at all (and that is completely out of scope of this tool). usbmount only tells the kernel to mount the filesystem, it has no control over how other application (mis)use the disk after that.

**Comment by thoschworks** [comment]
@mathieulj, I would read the description in the same way like you: not a problem of usbmount.

**Comment by Supr-A** [comment]
@mathieulj thank you for reply. I'll ask on MC tracker.

**Comment by thoschworks** [comment]
@AndreySu If it is not an issue with usbmount, can you close the issue, please.

**Comment by Supr-A** [comment]
Done

**Comment by thoschworks** [comment]
@AndreySu Thanks. :thumbsup:
